# This is a sync magiskboot lastest source with Actions push

name: update_upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "30 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        run: |
          sudo apt-get install -y git wget curl zip unzip ssh
          
      - name: Clone repo
        run: |
          git config --global user.email "2245062854@qq.com"
          git config --global user.name "xiaoxindada"
          ssh-keygen -t rsa -C "2245062854@qq.com"
          exit 1
          git clone --recurse-submodulesgit@github.com:xiaoxindada/magiskboot_ndk_on_linux.git magiskboot
          
      - name: update source and push
        run: |
          cd $GITHUB_WORKSPACE/magiskboot
          sudo ./build.sh update_code
          echo "::set-output name=status::succes"
     
      - name: push
        if: steps.organize.outputs.status == 'success' && !cancelled()
        run: |
          ssh -T git@github.com
          echo "UPDATE_TIME=$(date +%s)" >> $GITHUB_ENV
          git add .
          git commit -sm "Sync upstream code date:${{ env.UPDATE_TIME }}"
          
          
